### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by batpad** [moahmed/ezcms#3]
@moahmed would be nice to clarify what the license for this is, otherwise it becomes difficult for other people to use.

**Comment by moahmed** [comment]
yes, good one.

TODO: add GNU General Public License

On Tue, Feb 9, 2016 at 5:30 PM, Sanjay Bhangar notifications@github.com
wrote:

> @moahmed https://github.com/moahmed would be nice to clarify what the
> license for this is, otherwise it becomes difficult for other people to use.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/moahmed/ezcms/issues/3.

## 

Mohd Ahmed
_Director - HMI Technologies http://www.hmi-tech.net_

_Telephone number:_ +9122 - 2266-2313 / 2266-2601 / 2266-2875

_Office Working hours:_ Monday to Saturday; 10:00 AM to 6:00 PM

**Comment by moahmed** [comment]
@batpad I was looking for a good licence and came across this ...
https://github.com/batpad/jquery-rbox/blob/master/LICENSE

lol
